name: CI (test + build + push)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-app
  MAILER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-mailer

jobs:
  test:
    name: Run unit tests (Node)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Run tests with coverage
        run: npm test -- --coverage --config=jest.config.js

      - name: Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ===== APP: build + push =====
      - name: Build & Push APP
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appejs-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appejs-app:${{ github.sha }}

      # ===== MAILER: build + push (esto ya te funciona) =====
      - name: Build & Push MAILER
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.flask
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appejs-mailer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appejs-mailer:${{ github.sha }}


      # Si falla algo arriba, sube records del build
      - name: Export build records (if any)
        if: failure()
        run: |
          mkdir -p build-records
          docker buildx du --verbose || true
        shell: bash
