name: CI (test + build + push)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-app
  MAILER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-mailer

jobs:
  test:
    name: Run unit tests (Node)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Run tests with coverage
        run: npm test -- --coverage --config=jest.config.js

      - name: Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  docker:
    name: Build & Push images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Who am I in Docker?
        run: docker info && docker system df && echo "Docker user: $(docker whoami 2>/dev/null || echo unknown)"

      # ===== Build APP =====
      - name: Build APP (no push) to capture logs
        id: build_app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: false
          provenance: false
          tags: |
            ${{ env.APP_IMAGE }}:latest
            ${{ env.APP_IMAGE }}:${{ github.sha }}
          outputs: type=registry

      - name: Push APP
        run: |
          docker buildx build \
            --provenance=false \
            --file ./Dockerfile \
            --tag $APP_IMAGE:latest \
            --tag $APP_IMAGE:${GITHUB_SHA} \
            --push \
            .

      # ===== Build MAILER =====
      - name: Build MAILER (push)
        run: |
          docker buildx build \
            --provenance=false \
            --file ./Dockerfile.flask \
            --tag $MAILER_IMAGE:latest \
            --tag $MAILER_IMAGE:${GITHUB_SHA} \
            --push \
            .

      # Si falla algo arriba, sube records del build
      - name: Export build records (if any)
        if: failure()
        run: |
          mkdir -p build-records
          docker buildx du --verbose || true
        shell: bash
