name: Build & Push Docker images

on:
  push:
    branches: [ "main" ]        
  pull_request:
    branches: [ "main" ]       

env:
  APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-app
  MAILER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/appejs-mailer

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ===== Build & Push APP (Node) =====
      - name: Build & Push App image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.APP_IMAGE }}:latest
            ${{ env.APP_IMAGE }}:${{ github.sha }}

      # ===== Build & Push MAILER (Flask) =====
      - name: Build & Push Mailer image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.flask
          push: true
          tags: |
            ${{ env.MAILER_IMAGE }}:latest
            ${{ env.MAILER_IMAGE }}:${{ github.sha }}
